import type { WorkspaceDocument, WorkspaceSettings } from "@/lib/workspace-settings";

const NOW = "2026-03-16T17:00:00.000Z";
const TODAY = "2026-03-16";

export const PREVIEW_WORKSPACE_SETTINGS: WorkspaceSettings = {
  booking_link: "https://calendly.com/lockboxhq/demo-call",
  hot_lead_notification_mode: "business_hours",
  hot_lead_business_hours_start: "09:00",
  hot_lead_business_hours_end: "18:00",
  instagram_url: "https://instagram.com/lockboxhq",
  facebook_url: "https://facebook.com/lockboxhq",
  tiktok_url: "https://tiktok.com/@lockboxhq",
  saved_scripts: [
    {
      id: "preview-seller-opener",
      title: "Seller opener",
      category: "seller_outreach",
      body:
        "Thanks for reaching out. I looked over what you sent and would love to learn a little more about the property and your timing. Is a quick call or text easier today?",
    },
    {
      id: "preview-buyer-blast",
      title: "Buyer blast",
      category: "buyer_blast",
      body:
        "New opportunity available. Reply if you want the address, price guidance, and access details.",
    },
    {
      id: "preview-follow-up",
      title: "General follow-up",
      category: "follow_up",
      body:
        "Checking back in to see if this is still on your radar. If the timing changed, no problem — I can adjust the follow-up plan.",
    },
  ],
  documents: [],
};

export const PREVIEW_LEADS = [
  {
    id: "preview-lead-1",
    full_name: "Jordan Mitchell",
    first_name: "Jordan",
    last_name: "Mitchell",
    canonical_email: "jordan@example.com",
    canonical_phone: "(615) 555-0101",
    ig_username: "jordanhomes",
    lead_temp: "Hot",
    stage: "Contacted",
    source: "instagram",
    intent: "Buy",
    timeline: "0-3 months",
    location_area: "East Nashville",
    budget_range: "$500k-$700k",
    notes: "Preview lead for design review. Wants to move quickly and prefers text first.",
    time_last_updated: NOW,
    source_detail: {
      tags: ["buyer", "active buyer", "instagram"],
    },
  },
  {
    id: "preview-lead-2",
    full_name: "Avery Brooks",
    first_name: "Avery",
    last_name: "Brooks",
    canonical_email: "avery@example.com",
    canonical_phone: "(615) 555-0102",
    ig_username: null,
    lead_temp: "Warm",
    stage: "Qualified",
    source: "facebook",
    intent: "Sell",
    timeline: "3-6 months",
    location_area: "Green Hills",
    budget_range: "$900k-$1.1M",
    notes: "Preview seller lead with a property in Green Hills and a mid-term move window.",
    time_last_updated: "2026-03-15T14:30:00.000Z",
    source_detail: {
      tags: ["seller", "motivated seller", "facebook"],
    },
  },
  {
    id: "preview-lead-3",
    full_name: "Chloe Bennett",
    first_name: "Chloe",
    last_name: "Bennett",
    canonical_email: "chloe@example.com",
    canonical_phone: "(615) 555-0103",
    ig_username: null,
    lead_temp: "Cold",
    stage: "New",
    source: "referral",
    intent: "Invest",
    timeline: "6+ months",
    location_area: "Franklin",
    budget_range: "$750k-$1M",
    notes: "Preview long-term investor lead for lower-priority queue states.",
    time_last_updated: "2026-03-14T11:00:00.000Z",
    source_detail: {
      tags: ["investor", "referral"],
    },
  },
] as const;

export const PREVIEW_DEALS = [
  {
    id: "preview-deal-1",
    agent_id: "preview-agent",
    lead_id: "preview-lead-1",
    property_address: "412 Oak Street",
    price: 625000,
    stage: "new",
    deal_type: "buyer",
    notes: "Buyer inquiry created from Instagram with active showing interest.",
    updated_at: NOW,
    expected_close_date: TODAY,
    created_at: "2026-03-15T12:00:00.000Z",
    lead: PREVIEW_LEADS[0],
  },
  {
    id: "preview-deal-2",
    agent_id: "preview-agent",
    lead_id: "preview-lead-2",
    property_address: "18 Willow Ridge",
    price: 985000,
    stage: "under_contract",
    deal_type: "listing",
    notes: "Seller deal under contract and ready for next document check.",
    updated_at: "2026-03-13T10:00:00.000Z",
    expected_close_date: "2026-04-04",
    created_at: "2026-03-10T09:00:00.000Z",
    lead: PREVIEW_LEADS[1],
  },
] as const;

export const PREVIEW_RECOMMENDATIONS = [
  {
    id: "preview-rec-1",
    lead_id: "preview-lead-1",
    title: "Call Jordan this afternoon",
    description: "Buyer is in a 0-3 month timeframe and asked to see East Nashville options.",
    priority: "urgent",
    due_at: TODAY,
    metadata: {
      source_channel: "instagram",
      temperature: "Hot",
    },
  },
  {
    id: "preview-rec-2",
    lead_id: "preview-lead-2",
    title: "Review seller docs before next call",
    description: "Make sure the agreement and checklist stay visible before the follow-up.",
    priority: "high",
    due_at: TODAY,
    metadata: {
      source_channel: "facebook",
      temperature: "Warm",
    },
  },
  {
    id: "preview-rec-3",
    lead_id: "preview-lead-3",
    title: "Set a later nurture reminder",
    description: "Longer-term investor inquiry does not need immediate action, but should stay organized.",
    priority: "low",
    due_at: "2026-03-20",
    metadata: {
      source_channel: "referral",
      temperature: "Cold",
    },
  },
] as const;

export const PREVIEW_INTAKE_SUBMISSIONS = [
  {
    id: "preview-submission-1",
    lead_name: "Jordan Mitchell",
    source: "instagram",
    is_sample_workspace: true,
    intent: "Buy",
    timeline: "0-3 months",
    temperature: "Hot",
    stage: "Contacted",
    property_context: "East Nashville",
    budget_range: "$500k-$700k",
    deal_id: "preview-deal-1",
    deal_stage: "New",
    next_action: "Text first",
    next_action_detail: "Send East Nashville options, then call this afternoon.",
    next_action_priority: "urgent",
    next_action_due_at: TODAY,
    timestamp: NOW,
  },
  {
    id: "preview-submission-2",
    lead_name: "Avery Brooks",
    source: "facebook",
    is_sample_workspace: true,
    intent: "Sell",
    timeline: "3-6 months",
    temperature: "Warm",
    stage: "Qualified",
    property_context: "18 Willow Ridge",
    budget_range: "$900k-$1.1M",
    deal_id: "preview-deal-2",
    deal_stage: "Under Contract",
    next_action: "Review documents",
    next_action_detail: "Keep agreement and checklist visible before the seller follow-up.",
    next_action_priority: "high",
    next_action_due_at: TODAY,
    timestamp: "2026-03-15T14:30:00.000Z",
  },
] as const;

export const PREVIEW_DOCUMENTS: Array<WorkspaceDocument & { signed_url?: string | null }> = [
  {
    id: "preview-doc-1",
    file_name: "Purchase Agreement.pdf",
    storage_path: "preview/purchase-agreement.pdf",
    file_type: "agreement",
    deal_id: "preview-deal-2",
    lead_id: "preview-lead-2",
    tags: ["agreement", "seller"],
    status: "sent",
    mime_type: "application/pdf",
    size_bytes: 248000,
    uploaded_at: "2026-03-15T13:00:00.000Z",
    uploaded_by: "LockboxHQ Preview",
    signed_url: null,
  },
  {
    id: "preview-doc-2",
    file_name: "Closing Checklist.xlsx",
    storage_path: "preview/closing-checklist.xlsx",
    file_type: "checklist",
    deal_id: "preview-deal-2",
    lead_id: "preview-lead-2",
    tags: ["closing", "checklist"],
    status: "draft",
    mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    size_bytes: 88210,
    uploaded_at: NOW,
    uploaded_by: "LockboxHQ Preview",
    signed_url: null,
  },
];
