export type FormFieldType = "text" | "tel" | "email" | "select" | "radio" | "textarea";

export type FormField = {
  id: string;
  label: string;
  type: FormFieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  tooltip?: string;
  crm_field?: string;
  showIf?: { field: string; values: string[] };
};

export type FormTemplate = {
  form_type: string;
  title: string;
  headline?: string;
  description?: string;
  intent?: string;
  fields: FormField[];
};

const TIMELINE_OPTIONS = [
  "Within 30 days",
  "1-3 months",
  "3-6 months",
  "No rush",
];

const PROPERTY_TYPE_OPTIONS = [
  "Single Family Home",
  "Condo / Townhome",
  "Multi-Family",
  "Land Only",
  "Commercial",
  "Other",
];

export const FORM_TEMPLATES: Record<string, FormTemplate> = {
  generic_seller: {
    form_type: "generic_seller",
    title: "Seller Inquiry",
    description: "Tell us about your property and we'll follow up with the right next step.",
    intent: "Sell",
    fields: [
      {
        id: "property_address",
        label: "Property Address",
        type: "text",
        required: true,
        placeholder: "123 Main St, Nashville, TN",
        crm_field: "property_context",
      },
      {
        id: "property_type",
        label: "Property Type",
        type: "select",
        required: true,
        options: PROPERTY_TYPE_OPTIONS,
        crm_field: "property_type",
      },
      {
        id: "estimated_condition",
        label: "Estimated Condition",
        type: "select",
        required: true,
        options: ["Move-in Ready", "Needs Work", "Major Repairs", "Tear Down"],
        crm_field: "seller_readiness",
      },
      {
        id: "timeline",
        label: "Timeline to Sell",
        type: "select",
        required: true,
        options: TIMELINE_OPTIONS,
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  generic_buyer: {
    form_type: "generic_buyer",
    title: "Buyer Inquiry",
    description: "Share a few details and we'll match you with the right properties and next steps.",
    intent: "Buy",
    fields: [
      {
        id: "location_area",
        label: "Areas or ZIP Codes You're Interested In",
        type: "text",
        required: true,
        placeholder: "East Nashville, 37206, Green Hills...",
        crm_field: "location_area",
      },
      {
        id: "property_type",
        label: "Property Type",
        type: "select",
        required: true,
        options: PROPERTY_TYPE_OPTIONS,
        crm_field: "property_type",
      },
      {
        id: "budget_range",
        label: "Budget Range",
        type: "select",
        required: true,
        options: [
          "Under $200k",
          "$200k–$350k",
          "$350k–$500k",
          "$500k–$750k",
          "$750k–$1M",
          "$1M+",
        ],
        crm_field: "budget_range",
      },
      {
        id: "bedrooms",
        label: "Bedrooms Needed",
        type: "select",
        required: true,
        options: ["1", "2", "3", "4", "5+"],
      },
      {
        id: "financing_status",
        label: "Pre-Approved?",
        type: "radio",
        required: true,
        options: ["Yes", "No", "Not yet"],
        crm_field: "financing_status",
      },
      {
        id: "timeline",
        label: "Timeline to Buy",
        type: "select",
        required: true,
        options: TIMELINE_OPTIONS,
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  combo_sell_buy: {
    form_type: "combo_sell_buy",
    title: "Buy, Sell, or Both?",
    description: "Tell us what you're looking to do and we'll tailor the next steps.",
    fields: [
      {
        id: "intent_type",
        label: "What are you looking to do?",
        type: "radio",
        required: true,
        options: ["Buy", "Sell", "Both"],
        crm_field: "intent",
      },
      // Seller fields
      {
        id: "property_address",
        label: "Property Address",
        type: "text",
        required: false,
        placeholder: "123 Main St, Nashville, TN",
        crm_field: "property_context",
        showIf: { field: "intent_type", values: ["Sell", "Both"] },
      },
      {
        id: "property_type_sell",
        label: "Property Type",
        type: "select",
        required: false,
        options: PROPERTY_TYPE_OPTIONS,
        crm_field: "property_type",
        showIf: { field: "intent_type", values: ["Sell", "Both"] },
      },
      {
        id: "estimated_condition",
        label: "Estimated Condition",
        type: "select",
        required: false,
        options: ["Move-in Ready", "Needs Work", "Major Repairs", "Tear Down"],
        crm_field: "seller_readiness",
        showIf: { field: "intent_type", values: ["Sell", "Both"] },
      },
      // Buyer fields
      {
        id: "location_area",
        label: "Areas or ZIP Codes You're Interested In",
        type: "text",
        required: false,
        placeholder: "East Nashville, 37206...",
        crm_field: "location_area",
        showIf: { field: "intent_type", values: ["Buy", "Both"] },
      },
      {
        id: "budget_range",
        label: "Budget Range",
        type: "select",
        required: false,
        options: ["Under $200k", "$200k–$350k", "$350k–$500k", "$500k–$750k", "$750k–$1M", "$1M+"],
        crm_field: "budget_range",
        showIf: { field: "intent_type", values: ["Buy", "Both"] },
      },
      {
        id: "financing_status",
        label: "Pre-Approved?",
        type: "radio",
        required: false,
        options: ["Yes", "No", "Not yet"],
        crm_field: "financing_status",
        showIf: { field: "intent_type", values: ["Buy", "Both"] },
      },
      // Shared
      {
        id: "timeline",
        label: "Timeline",
        type: "select",
        required: true,
        options: TIMELINE_OPTIONS,
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  rural_land_seller: {
    form_type: "rural_land_seller",
    title: "Land & Rural Property Inquiry",
    headline: "Thinking about selling your land or property? Get a cash offer range in 24 hours — no obligation, no agent fees.",
    description: "Tell us about your property and we'll follow up with a realistic offer range.",
    intent: "Sell",
    fields: [
      {
        id: "property_address",
        label: "Property Address",
        type: "text",
        required: true,
        placeholder: "Address or rural route",
        crm_field: "property_context",
      },
      {
        id: "acreage",
        label: "Acreage / Lot Size",
        type: "text",
        required: true,
        placeholder: "e.g. 12.5 acres",
      },
      {
        id: "property_type",
        label: "Property Type",
        type: "select",
        required: true,
        options: ["Single Family Home", "Land Only", "Farm / Ranch", "Mobile Home", "Multi-Family", "Other"],
        crm_field: "property_type",
      },
      {
        id: "septic_sewer",
        label: "Septic or Sewer?",
        type: "select",
        required: true,
        options: ["Septic", "Connected to Sewer", "Neither / Unknown"],
      },
      {
        id: "water_source",
        label: "Water Source?",
        type: "select",
        required: true,
        options: ["City / Municipal Water", "Well", "Neither / Unknown"],
      },
      {
        id: "perc_test",
        label: "Perc Test Completed?",
        type: "select",
        required: true,
        options: ["Yes", "No", "Don't Know"],
        tooltip: "A perc test determines if the land can support a septic system.",
      },
      {
        id: "owners_on_title",
        label: "How Many Owners on the Title?",
        type: "select",
        required: true,
        options: ["1", "2", "3+"],
      },
      {
        id: "timeline",
        label: "Timeline to Sell",
        type: "select",
        required: true,
        options: [
          "Within 30 days",
          "1-3 months",
          "3-6 months",
          "No rush — just exploring my options",
        ],
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  distressed_wholesale: {
    form_type: "distressed_wholesale",
    title: "Distressed Property Inquiry",
    description: "We work with properties in any condition. Share what you can and we'll be in touch quickly.",
    intent: "Sell",
    fields: [
      {
        id: "property_address",
        label: "Property Address",
        type: "text",
        required: true,
        placeholder: "123 Main St",
        crm_field: "property_context",
      },
      {
        id: "property_type",
        label: "Property Type",
        type: "select",
        required: true,
        options: PROPERTY_TYPE_OPTIONS,
        crm_field: "property_type",
      },
      {
        id: "estimated_condition",
        label: "Estimated Condition",
        type: "select",
        required: true,
        options: ["Needs Major Repairs", "Structural Issues", "Fire or Water Damage", "Tear Down"],
        crm_field: "seller_readiness",
      },
      {
        id: "behind_on_payments",
        label: "Behind on Payments?",
        type: "radio",
        required: true,
        options: ["Yes", "No", "Prefer not to say"],
      },
      {
        id: "foreclosure_filed",
        label: "Foreclosure Filed?",
        type: "radio",
        required: true,
        options: ["Yes", "No", "Not sure"],
      },
      {
        id: "occupancy",
        label: "Occupied or Vacant?",
        type: "select",
        required: true,
        options: ["Owner Occupied", "Tenant Occupied", "Vacant"],
      },
      {
        id: "timeline",
        label: "Timeline",
        type: "select",
        required: true,
        options: TIMELINE_OPTIONS,
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  probate_inherited: {
    form_type: "probate_inherited",
    title: "Inherited Property Inquiry",
    description: "We work with heirs, executors, and attorneys to simplify inherited property situations.",
    intent: "Sell",
    fields: [
      {
        id: "property_address",
        label: "Property Address",
        type: "text",
        required: true,
        placeholder: "123 Main St",
        crm_field: "property_context",
      },
      {
        id: "property_type",
        label: "Property Type",
        type: "select",
        required: true,
        options: PROPERTY_TYPE_OPTIONS,
        crm_field: "property_type",
      },
      {
        id: "relationship_to_owner",
        label: "Your Relationship to the Owner",
        type: "select",
        required: true,
        options: ["Heir", "Executor", "Attorney", "Other"],
      },
      {
        id: "probate_filed",
        label: "Is Probate Filed?",
        type: "radio",
        required: true,
        options: ["Yes", "No", "In progress"],
      },
      {
        id: "attorney_involved",
        label: "Is an Attorney Involved?",
        type: "radio",
        required: true,
        options: ["Yes", "No"],
      },
      {
        id: "number_of_heirs",
        label: "Number of Heirs Involved",
        type: "select",
        required: true,
        options: ["1", "2", "3+"],
      },
      {
        id: "timeline",
        label: "Timeline",
        type: "select",
        required: true,
        options: TIMELINE_OPTIONS,
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  commercial_multifamily: {
    form_type: "commercial_multifamily",
    title: "Commercial & Multi-Family Inquiry",
    description: "Share your property details and we'll follow up with the right buyer or next step.",
    intent: "Sell",
    fields: [
      {
        id: "property_address",
        label: "Property Address",
        type: "text",
        required: true,
        placeholder: "123 Main St",
        crm_field: "property_context",
      },
      {
        id: "property_type",
        label: "Property Type",
        type: "select",
        required: true,
        options: ["Multi-Family", "Mixed-Use", "Commercial Lot", "Office", "Retail", "Other"],
        crm_field: "property_type",
      },
      {
        id: "num_units",
        label: "Number of Units",
        type: "text",
        required: true,
        placeholder: "e.g. 12",
      },
      {
        id: "occupancy_pct",
        label: "Current Occupancy %",
        type: "text",
        required: true,
        placeholder: "e.g. 85",
      },
      {
        id: "estimated_noi",
        label: "Estimated NOI (if known)",
        type: "text",
        required: false,
        placeholder: "e.g. $120,000 / year",
      },
      {
        id: "zoning",
        label: "Zoning",
        type: "text",
        required: false,
        placeholder: "e.g. MU-4, C-2",
      },
      {
        id: "timeline",
        label: "Timeline",
        type: "select",
        required: true,
        options: TIMELINE_OPTIONS,
        crm_field: "timeline",
      },
      {
        id: "first_name",
        label: "First Name",
        type: "text",
        required: true,
        placeholder: "Your first name",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel",
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email",
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
    ],
  },

  off_market_seller: {
    form_type: "off_market_seller",
    title: "Seller Inquiry",
    description:
      "Tell us about your property and we'll follow up with next steps — no obligation.",
    intent: "Sell",
    fields: [
      {
        id: "full_name",
        label: "Full Name",
        type: "text" as const,
        required: true,
        placeholder: "Jane Smith",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel" as const,
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email" as const,
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
      {
        id: "property_address",
        label: "Property Address",
        type: "text" as const,
        required: true,
        placeholder: "123 Main St, Nashville, TN",
        crm_field: "property_context",
      },
      {
        id: "acreage",
        label: "Acreage / Lot Size",
        type: "text" as const,
        required: false,
        placeholder: "e.g. 12.5 acres",
        crm_field: "custom.acreage",
      },
      {
        id: "asking_price",
        label: "Asking Price",
        type: "text" as const,
        required: false,
        placeholder: "e.g. $350,000",
        crm_field: "custom.asking_price",
      },
      {
        id: "notes",
        label: "Additional Notes",
        type: "textarea" as const,
        required: false,
        placeholder: "Anything else we should know about the property?",
        crm_field: "notes",
      },
    ],
  },

  off_market_buyer: {
    form_type: "off_market_buyer",
    title: "Buyer Inquiry",
    description:
      "Share what you're looking for and we'll reach out with matching opportunities.",
    intent: "Buy",
    fields: [
      {
        id: "full_name",
        label: "Full Name",
        type: "text" as const,
        required: true,
        placeholder: "Jane Smith",
        crm_field: "full_name",
      },
      {
        id: "phone",
        label: "Phone Number",
        type: "tel" as const,
        required: true,
        placeholder: "(615) 555-0100",
        crm_field: "phone",
      },
      {
        id: "email",
        label: "Email Address",
        type: "email" as const,
        required: false,
        placeholder: "you@email.com",
        crm_field: "email",
      },
      {
        id: "budget_range",
        label: "Price Range",
        type: "select" as const,
        required: true,
        options: [
          "Under $200k",
          "$200k–$350k",
          "$350k–$500k",
          "$500k–$750k",
          "$750k–$1M",
          "$1M+",
        ],
        crm_field: "budget_range",
      },
      {
        id: "location_area",
        label: "Location Preference",
        type: "text" as const,
        required: true,
        placeholder: "Areas, cities, or ZIP codes you're interested in",
        crm_field: "location_area",
      },
      {
        id: "notes",
        label: "Additional Notes",
        type: "textarea" as const,
        required: false,
        placeholder: "Any specifics about what you're looking for?",
        crm_field: "notes",
      },
    ],
  },
};

export const FORM_ROUTER_OPTIONS = [
  { label: "I want to sell my home", form_type: "generic_seller" },
  { label: "I want to sell land or rural property", form_type: "rural_land_seller" },
  { label: "I'm looking to buy", form_type: "generic_buyer" },
  { label: "I want to sell a distressed property", form_type: "distressed_wholesale" },
  { label: "I inherited a property", form_type: "probate_inherited" },
  { label: "I have a commercial property", form_type: "commercial_multifamily" },
] as const;
